services:
  chat-db:
    image: kamil20/chat-db
    container_name: chat-db
    build:
      context: ./db
    restart: always
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_PORT: ${DB_PORT}
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: -p ${DB_PORT}

  messages-queue:
    image: kamil20/messages-queue
    container_name: messages-queue
    build:
      context: ./messages-queue
    restart: always
    volumes:
      - ./data/queue/data:/var/lib/rabbitmq
      - ./data/queue/log:/var/log/rabbitmq
    ports:
      - "5672:5672"   # Listen messages port
      - "15672:15672" # Management port
      - "61613:61613" # Stomp port

  chat-backend-sender:
    image: kamil20/chat-backend-sender-compose
    container_name: chat-backend-sender
    build:
      context: ./backend-sender
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://chat-db:${DB_PORT}/${DB}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_RABBITMQ_HOST: messages-queue
      SPRING_RABBITMQ_PORT: ${MESSAGES_QUEUE_PORT}
      SPRING_RABBITMQ_USERNAME: ${MESSAGES_QUEUE_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${MESSAGES_QUEUE_PASSWORD}
      SPRING_RABBITMQ_TEMPLATE_EXCHANGE: ${MESSAGES_QUEUE_EXCHANGE}
      RABBITMQ_CHAT_ROUTINGKEY: ${MESSAGES_QUEUE_ROUTINGKEY}
      PORT: ${BACKEND_SENDER_PORT}
    ports:
      - "${BACKEND_SENDER_PORT}:${BACKEND_SENDER_PORT}"
    depends_on:
      - chat-db
      - messages-queue
  
  chat-backend-receiver:
    image: kamil20/chat-backend-receiver
    container_name: chat-backend-receiver
    build:
      context: ./backend-receiver
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: messages-queue
      SPRING_RABBITMQ_PORT: ${MESSAGES_QUEUE_PORT}
      SPRING_RABBITMQ_USERNAME: ${MESSAGES_QUEUE_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${MESSAGES_QUEUE_PASSWORD}
      RABBITMQ_CHAT_QUEUE_NAME: chat.queue
      RABBITMQ_STOMP_PORT: 61613
      PORT: ${BACKEND_RECEIVER_PORT}
    ports:
      - "${BACKEND_RECEIVER_PORT}:${BACKEND_RECEIVER_PORT}"
    depends_on:
      - chat-backend-sender

  chat-frontend:
    image: kamil20/chat-frontend
    container_name: chat-frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - "3100:3100"
    depends_on:
      - chat-backend-sender