version: '3.9'
include:
 - ./code/instagram/docker-compose.yml
 - ./code/chat/docker-compose.yaml

services:
  db-pgadmin:
    image: dpage/pgadmin4
    container_name: instagram-db-management
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: instagram
    volumes:
      - ./database/management-data:/var/lib/pgadmin
